### ISSUE TITLE
IProgress is not available with IArchiveExtractCallback

### ISSUE THREAD

**Issue by remyroy** [harvimt/pylib7zip#3]
It would be nice to have access to the IProgress callbacks in Python while extracting an archive.

Use cases for this include showing extraction progress to the end user in a UI.

**Comment by remyroy** [comment]
I've just noticed that it is available with `ArchiveExtractCallback` in `lib7zip.extract_callback`. I'm guessing I will have to inherit from that class and reimplement `ArchiveItem.extract` to use the new class if I want to have access to the callbacks.

**Comment by harvimt** [comment]
That's how the entire 7Zip API works internally. I tried to sort of hide it with my python API, but it's hard.

It would have been easier to deal with if it had been functions that take in file pointers or structs of file pointers, but they use C++ classes instead.
